# This file was generated by GoReleaser. DO NOT EDIT.
cask "shipyard" do
  desc "A tool to manage Ephemeral Environments on the Shipyard platform"
  homepage "https://shipyard.build"
  version "1.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shipyard"

  on_macos do
    on_intel do
      url "https://github.com/shipyard/shipyard-cli/releases/download/v1.8.0/shipyard-cli_1.8.0_darwin_amd64.tar.gz"
      sha256 "6040a3fc91e9c66c3ba7ee5b991ae715a32d17694074852104b4ef561dc99866"
    end
    on_arm do
      url "https://github.com/shipyard/shipyard-cli/releases/download/v1.8.0/shipyard-cli_1.8.0_darwin_arm64.tar.gz"
      sha256 "830e61692e3f53ece4925a68c259968d25ac4c04237c0eabdb1cedf9399ce0ab"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/shipyard/shipyard-cli/releases/download/v1.8.0/shipyard-cli_1.8.0_linux_amd64.tar.gz"
      sha256 "54fe45b17880b043ed725dc1cb34bb3038d34ade51fec6a14847a3242d11ffc3"
    end
    on_arm do
      url "https://github.com/shipyard/shipyard-cli/releases/download/v1.8.0/shipyard-cli_1.8.0_linux_arm64.tar.gz"
      sha256 "ca364c3e7023524fb358449e595dc212cfdebe0edef6fa1c351b9e977b1c2e42"
    end
  end

  # No zap stanza required
end
