# This file was generated by GoReleaser. DO NOT EDIT.
cask "shipyard" do
  desc "A tool to manage Ephemeral Environments on the Shipyard platform"
  homepage "https://shipyard.build"
  version "1.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shipyard"

  on_macos do
    on_intel do
      url "https://github.com/shipyard/shipyard-cli/releases/download/v1.8.0/shipyard-darwin-amd64.zip"
      sha256 "77634d6096a6d61093c92fbcd31e8fe62a194563bb3f900f3a1ad31e44cca095"
    end
    on_arm do
      url "https://github.com/shipyard/shipyard-cli/releases/download/v1.8.0/shipyard-darwin-arm64.zip"
      sha256 "298f606266e503a32fd0462e767ffe0ad9fa6f1fe770274618dc3423e2afc101"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/shipyard/shipyard-cli/releases/download/v1.8.0/shipyard-linux-amd64.tar.gz"
      sha256 "6c50d7a3d7bc434af86cb83d87236d94709bb59fcac4efdff845697b10927dda"
    end
    on_arm do
      url "https://github.com/shipyard/shipyard-cli/releases/download/v1.8.0/shipyard-linux-arm64.tar.gz"
      sha256 "82be96302e01b747d3940f04c8ff10b5c999a0da5b8d14d878fa69cf1de76956"
    end
  end

  # No zap stanza required
end
