# This file was generated by GoReleaser. DO NOT EDIT.
cask "shipyard" do
  version "1.8.1"

  on_macos do
    on_intel do
      sha256 "55f46b0daac51b7db265a40d2ee7d9b2eea67ec144ec543d2f0b64a019d8335d"
      url "https://github.com/shipyard/shipyard-cli/releases/download/v#{version}/shipyard-darwin-amd64"
      binary "shipyard-darwin-amd64", target: "shipyard-darwin-amd64"
    end
    on_arm do
      sha256 "2e07a80201f85077d16802a11e69dc1c6537e208c7de244de7b9a32ef69263a0"
      url "https://github.com/shipyard/shipyard-cli/releases/download/v#{version}/shipyard-darwin-arm64"
      binary "shipyard-darwin-arm64", target: "shipyard-darwin-arm64"
    end
  end

  on_linux do
    on_intel do
      sha256 "671910194b18bb48230101f9d6640faf7eda630380477730df18af44c279bfc8"
      url "https://github.com/shipyard/shipyard-cli/releases/download/v#{version}/shipyard-linux-amd64"
      binary "shipyard-linux-amd64", target: "shipyard-linux-amd64"
    end
    on_arm do
      sha256 "9bdbb6b4c5ea8bbadd03cd135713c3878f8a092fcec8641860dcea11968d518d"
      url "https://github.com/shipyard/shipyard-cli/releases/download/v#{version}/shipyard-linux-arm64"
      binary "shipyard-linux-arm64", target: "shipyard-linux-arm64"
    end
  end

  name "shipyard"
  desc "A tool to manage Ephemeral Environments on the Shipyard platform"
  homepage "https://shipyard.build"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
