# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShipyardCli < Formula
  desc "A tool to manage Ephemeral Environments on the Shipyard platform"
  homepage "https://shipyard.build"
  version "1.2.0"
  license "Apache2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shipyardbuild/shipyard-cli/releases/download/v1.2.0/shipyard-darwin-arm64", using: CurlDownloadStrategy
      sha256 "ce7d33b204203360f1dee61b42bc170c5db92ca2c76d2a21506e695a4ede339d"

      def install
        bin.install "shipyard"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shipyardbuild/shipyard-cli/releases/download/v1.2.0/shipyard-darwin-amd64", using: CurlDownloadStrategy
      sha256 "d4fe789a9e366d48784286c708b56c70c32653ea54289d3900609ec2cfa61dae"

      def install
        bin.install "shipyard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shipyardbuild/shipyard-cli/releases/download/v1.2.0/shipyard-linux-arm64", using: CurlDownloadStrategy
      sha256 "14e76094987080f07487b8cb390f8526a32cdd60416d8a97235a6c7e0407b980"

      def install
        bin.install "shipyard"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shipyardbuild/shipyard-cli/releases/download/v1.2.0/shipyard-linux-amd64", using: CurlDownloadStrategy
      sha256 "a05a609b1a19ef4549a2fb1918c4c71722a9a99442f50462ef21894e348b5a0a"

      def install
        bin.install "shipyard"
      end
    end
  end
end
