# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shipyard < Formula
  desc "A tool to manage Ephemeral Environments on the Shipyard platform"
  homepage "https://shipyard.build"
  version "1.3.0"
  license "Apache2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shipyard/shipyard-cli/releases/download/v1.3.0/shipyard-darwin-amd64"
      sha256 "17ccd1ab0858f4a61f1def674c45ccfa5c0cc5e343015b11ff7034fa756b6d33"

      def install
        bin.install "shipyard-darwin-amd64" => "shipyard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shipyard/shipyard-cli/releases/download/v1.3.0/shipyard-darwin-arm64"
      sha256 "45769993c2629a0bd43aee6163e3d233914bfd1eb2b63e6438619991e91f3bae"

      def install
        bin.install "shipyard-darwin-arm64" => "shipyard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shipyard/shipyard-cli/releases/download/v1.3.0/shipyard-linux-amd64"
      sha256 "5b8c77c1a6e4f9b76d0c3b3e36bbcd6e9f9522e5d5606b1458893c2e91855b45"

      def install
        bin.install "shipyard-linux-amd64" => "shipyard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shipyard/shipyard-cli/releases/download/v1.3.0/shipyard-linux-arm64"
      sha256 "43f42e1a7b1c91bed22017570b9f5b6fbe5a8d4200efea0cff5b386e72287d8b"

      def install
        bin.install "shipyard-linux-arm64" => "shipyard"
      end
    end
  end
end
