# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shipyard < Formula
  desc "A tool to manage Ephemeral Environments on the Shipyard platform"
  homepage "https://shipyard.build"
  version "1.2.1"
  license "Apache2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shipyard/shipyard-cli/releases/download/v1.2.1/shipyard-darwin-amd64"
      sha256 "0630cc01ab6699a7674e7d1a9ed067525e1245b18c9f3ffd2a938afd2582063e"

      def install
        bin.install "shipyard-darwin-amd64" => "shipyard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shipyard/shipyard-cli/releases/download/v1.2.1/shipyard-darwin-arm64"
      sha256 "8803b66f6debf56fe9bbaeeb0edfc924a2e2c6256d64741e4c053efe982dfe6e"

      def install
        bin.install "shipyard-darwin-arm64" => "shipyard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shipyard/shipyard-cli/releases/download/v1.2.1/shipyard-linux-amd64"
      sha256 "815a6e13996538124ee1b504fee743437054c1e5904df3aafdc7772125b2844b"

      def install
        bin.install "shipyard-linux-amd64" => "shipyard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shipyard/shipyard-cli/releases/download/v1.2.1/shipyard-linux-arm64"
      sha256 "146ed9063e546891e02e9975cf6883404f9150a6e332743d5ea6e69379711f37"

      def install
        bin.install "shipyard-linux-arm64" => "shipyard"
      end
    end
  end
end
